version: '3'
services:
  neo4j:
    image: neo4j:5.12.0
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf/neo4j.conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/admin1234

    networks:
      my_network:
  app:
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - neo4j
    networks:
      my_network:

networks:
  my_network:
